<li class="media ">
    <div class="container ml-0 pl-0 mr-0 pr-0 ">
        <div class="row list-element">


            <div class="media-body line-clamp col-sm-8 ml-0 pl-1 mr-0 pr-0" style="color: #ffc107">

                <a href= "/list" class="line-clamp text-center my-3 "  style="color: #ffc107" >
                    Nothing found - click and go to the recipes list
                </a>

            </div>
        </div>
    </div>
</li>