<footer>
    <div class="bottom-ft" id="bottom-ft">
        <div class="container container-fluid">

            <div class="row-copy">
                <br>
                <i style="color: white; text-align: center">
                    <#assign aDateTime = .now>
                    <#assign aDate = aDateTime?date>
                    Kamil, Łukasz , Szymon - Copyrights &copy; All reserved ${aDate?string.yyyy}.
                </i>
            </div>
        </div>
    </div>
</footer>