<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-signin-client_id" content=298114958760-uts75flcprffcondd1jqatnqvhdronhs.apps.googleusercontent.com>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>Not found</title>
    <link href="../../css/style.css" rel="stylesheet">
    <script src="https://kit.fontawesome.com/84fd5d585b.js" crossorigin="anonymous"></script>
    <script src="https://apis.google.com/js/platform.js" async defer></script>
</head>
<body id="page-top">

<#include "navigation.ftlh">

<div class="container-fluid" style="color:red; background-color: #1b1e21; text-align: center">
    <label><h2>Not found - code 404.</h2></label>
</div>

<div class="body part1-top" id="body part1-top" style="background-color: #1b1e21">
    <div class="container-fluid" id="part1-top">
        <div style="position: relative">
            <img class="backGround" src="../../img/mindhunters.jpg" alt="background" id="glasses">
            <div class="over-photo1">
                <header class="masthead">
                    <div class="container welcome-settings">
                        <div class="masthead-subheading  text-warning glow " id="welcomeDiv"
                             style=font-size:30px;text-align:center>
                            Welcome ${name ! "Stranger"}<br>
                            Page Not Found - 404.
                        </div>
                    </div>
                </header>
            </div>
        </div>
    </div>
</div>

<#include "footer.ftlh">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymneiw iem jak wsatawilem u mnie footer to mi namiesal z ustawieniemous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
<script src="../../js/homePage.js"></script>
</body>
</html>
